### ISSUE TITLE
What is the difference between this work and OSX?

### ISSUE THREAD

**Issue by Gel-smile** [caizhongang/SMPLer-X#12]
hi,
This result is very amazing. I would like to know other than the difference in training data, is there any difference between this work and OSX?

**Comment by caizhongang** [comment]
Hi @Gel-smile , SMPLer-X aims to study the effectiveness of data. Hence, it utilizes a **minimalistic** architecture, which is essentially OSX without the heavy decoder.

Hope this helps!

**Comment by jinpengchina** [comment]
I hope to make  action file(Smpl) to other human models. Is there an easy way or tutorial?

**Comment by Gel-smile** [comment]
OK，thanks

**Comment by caizhongang** [comment]
> I hope to make action file(Smpl) to other human models. Is there an easy way or tutorial?

@jinpengchina , if you are referring retargeting the SMPL-X motions to virtual characters, we are working on that. Please stay tuned! If you are referring to conversion between parametric human models (e.g. SMPL -> SMPL-X), please refer to the [official tools](https://github.com/vchoutas/smplx/tree/main/transfer_model).
