### ISSUE TITLE
about hand token

### ISSUE THREAD

**Issue by Dong09** [caizhongang/SMPLer-X#17]
hello, i just found that it does not use the **hand_token** variable by inference. Is this intentional?Because i get the hand result not well

**Comment by HonglinChu** [comment]
It seems that the hand pose is not good

**Comment by Dong09** [comment]
> It seems that the hand pose is not good

I would like to ask how this model is converted to ONNX, which is very important to me. I used the **torch.onnx.export** function to turn onnx, which neither saved onnx nor reported an error.

**Comment by buzuyun** [comment]
@Dong09 Hi, I'm encountering issues with torch.cross when exporting to ONNX. Could you share how you resolved this? Here's my pseudo code:

```python
input_names = ['input_img']
output_names = ['output']
dummy_input = ({'img': torch.randn(batch_size, 3, imheight, imwidth, device=device)}, {})
torch.onnx.export(model, dummy_input, onnx_path, verbose=verbose, input_names=input_names, output_names=output_names, opset_version=opset_version)
```

I found that in `torch.cross` it could not infer the shape of the first parameters, i.e., input.
```shell
[cross] input.sizes=[1, 3], other.sizes=[None, None], dim=1
[cross] input.sizes=[21, 3], other.sizes=[None, None], dim=1
[cross] input.sizes=[21, 3], other.sizes=[None, None], dim=1
[cross] input.sizes=[None, None], other.sizes=[None, None], dim=None # error, at `jaw_pose = rot6d_to_axis_angle(jaw_pose)`
```
