### ISSUE TITLE
Subtraction, the `-` operator, with a bool tensor is not supported.

### ISSUE THREAD

**Issue by ghx2757** [caizhongang/SMPLer-X#18]
May I ask if the following error occurred while loading the model? Is this an issue with the pytorch version or the model? How to solve it?

![截图 2023-10-20 11-49-29](https://github.com/caizhongang/SMPLer-X/assets/141898896/bacbe665-344b-47ec-855f-5e93f0a81bcb)

**Comment by bitxwb** [comment]
Have you sovled it? There is the same problem when I run the code.

**Comment by ghx2757** [comment]
Taking a look at the FAQ section, the author kindly provided a solution, and I have followed it to solve my aforementioned problem.

**Comment by bitxwb** [comment]
> Taking a look at the FAQ section, the author kindly provided a solution, and I have followed it to solve my aforementioned problem. @bitxwb

Thank you very much! I follow the method then it works. Wish you have a good day!
