### ISSUE TITLE
Pretrained model?

### ISSUE THREAD

**Issue by noeykan** [caizhongang/SMPLer-X#2]
Hi, thanks for sharing your great work!

Is there any pretrained model I can test?

**Comment by caizhongang** [comment]
@noeykan Thank you for your interest in SMPLer-X!

The pretrained models will be released very soon, please stayed tuned!

**Comment by noeykan** [comment]
@caizhongang Thanks for your reply! OK, I'll wait for that :)

**Comment by caizhongang** [comment]
@noeykan pretrained models have just been released. Please let us know if you encounter any problem.

**Comment by noeykan** [comment]
Thank you :)

**Comment by noeykan** [comment]
Do you have any plans in the future to release demo for inputting images and outputting images with pose meshes?

It could be really useful to check the result easily! Thanks.
