### ISSUE TITLE
Data converting scripts

### ISSUE THREAD

**Issue by GhostLate** [caizhongang/SMPLer-X#23]
Thank you for your work! Do you have any plans to release converters to the human_data format? (Most interested in the BEDLAM converter)

**Comment by Wei-Chen-hub** [comment]
Hi, currently the data processing pipeline is intended for internal use only as it is not well cleaned and documented.

If you are interested in human_data, the develop process is updated to [MMHuman3d](https://github.com/open-mmlab/mmhuman3d), branch "convertors".

The detailed format of HumanData is [here](https://github.com/open-mmlab/mmhuman3d/blob/convertors/docs/human_data.md).

And the currently data preprcess script is [here](https://github.com/open-mmlab/mmhuman3d/tree/convertors/mmhuman3d/data/data_converters).

Unfortunately bedlam is done by my colleague, for which i just collected his script and pushed to the above link, but i could not offer more insights in dataset details.

Hope that could address your concern.

**Comment by Wei-Chen-hub** [comment]
Close as resolved, feel free to open a new issue if it is related to smplerx. If you have any issue regarding to HumanData, please open issue in MMHuman3D. Thanks for your interest.
