### ISSUE TITLE
ImportError: ('Unable to load OpenGL library', "Could not find module 'OSMesa' (or one of its dependencies). Try using the full path with constructor syntax.", 'OSMesa', None)

### ISSUE THREAD

**Issue by rulke** [caizhongang/SMPLer-X#25]
The following error occurs when reasoning on windows10, please tell me how to solve it, thank you
![image](https://github.com/caizhongang/SMPLer-X/assets/93243962/854840fe-22bb-43c7-9249-862c61e6bae5)

**Comment by Wei-Chen-hub** [comment]
The inference was not tested on windows 10 directly, I suggest to install WSL2 for win10 which is same as mine.

If you really want to get the pipeline working in windows, you can try to delete anything related to pyrender and opengl in SMPLerX repo. We use pyrender to visualize mesh overlay and project keypoints, inference itself does not require pyrender.

**Comment by rulke** [comment]
> The inference was not tested on windows 10 directly, I suggest to install WSL2 for win10 which is same as mine.
> 
> If you really want to get the pipeline working in windows, you can try to delete anything related to pyrender and opengl in SMPLerX repo. We use pyrender to visualize mesh overlay and project keypoints, inference itself does not require pyrender.
Thank you for your reply. I will try it
