### ISSUE TITLE
Can not find SMPLX_to_J14.pkl in links

### ISSUE THREAD

**Issue by TrinityNeo99** [caizhongang/SMPLer-X#26]
Dear Author:
Thanks a lot for your job, when I download files as your README to construct human_models_files, I can not find the file "SMPLX_to_J14.pkl" in smplx. Could you please help me with that?

the link in README is https://smpl-x.is.tue.mpg.de/download.php

**Comment by zacida** [comment]
HI @TrinityNeo99 , all pretrained things and models could be found here: https://huggingface.co/camenduru/SMPLer-X/tree/main
