### ISSUE TITLE
FPS comparison with other SOTAs?

### ISSUE THREAD

**Issue by noeykan** [caizhongang/SMPLer-X#3]
Hi!

Do you have any comparison results of inference speed(fps) between your code and other SOTAs like OSX?

Thanks!

**Comment by caizhongang** [comment]
Hi @noeykan ,

Inference speed heavily depends on the hardware (GPU, CPU, RAM, etc) and we have not conducted tests on this matter.

However, we do recognize that this may interest the community. We'll keep you posted on any progress.

**Comment by noeykan** [comment]
@caizhongang Thank you for your reply.
Could you let me know if your algorithm's inference speed would be faster/similar/slower than OSX roughly?
The accuracy looks better, but I just want to know the relative inference speed compared to OSX.

**Comment by caizhongang** [comment]
@noeykan, our architecture is similar to the OSX (w.o. decoder). The inference speed also depends on the backbone. With backbone <= ViT-L, our inference speed should be as fast if not faster than OSX.

**Comment by caizhongang** [comment]
@noeykan , we have updated the inference speed for our foundation model. For OSX (ViT-L backbone) with the same setting, the FPS is 12.17.

**Comment by lucasjinreal** [comment]
It's that possible runs realtime on CPU?

**Comment by lucasjinreal** [comment]
what's more, how does the differences between compare with cliff PARE etc? (acccuracy)

**Comment by noeykan** [comment]
@caizhongang Thank you for your updates! Do you mean that your fps(24.4) is twice as fast as OSX(12.17) with Vit-L in the same setting? Good work!

**Comment by caizhongang** [comment]
> It's that possible runs realtime on CPU?

Hi @lucasjinreal , this is an interesting question, we will definitely look into it when we have the time. Currently, we do not have any experiments on this matter. If you have any findings, please let us know.

**Comment by caizhongang** [comment]
> @caizhongang Thank you for your updates! Do you mean that your fps(24.4) is twice as fast as OSX(12.17) with Vit-L in the same setting? Good work!

Yes, we conducted tests on a single V100 GPU to obtain the results.
