### ISSUE TITLE
Use Pytorch3D to render visualization

### ISSUE THREAD

**Issue by AndyWangZH** [caizhongang/SMPLer-X#36]
Firstly, I would like to express my admiration for your impressive work. It has been a great resource for me.

I am currently trying to understand how to use PyTorch3D for 2D overlap visualization. 

I have attempted to write my own code to achieve this, but the results have been unsatisfactory, with strange overlapping occurring. I suspect that I might be missing some crucial steps or misusing some parameters.

Could you possibly provide a detailed description or guide on how to use PyTorch3D for 2D overlap visualization, particularly with respect to the use of predicted camera parameters? Any examples or references would be greatly appreciated.

Thank you in advance for your time and assistance. I look forward to your response.

Best regards

**Comment by caizhongang** [comment]
Hi @AndyWangZH , you may refer to [MMHuman3D](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/core/visualization/visualize_smpl.py)for rendering a parametric model with PyTorch3D. 
However, we opt to use Pyrender as we do not need differentiable rendering and it is more lightweight.
