### ISSUE TITLE
如何为虚拟角色制作动画

### ISSUE THREAD

**Issue by ruolunhui** [caizhongang/SMPLer-X#38]
想请教下如何转换为动画，比较小白，想知道一条路径，不需要非常详细，能大概告知如何操作的就行，非常感谢

**Comment by ruolunhui** [comment]
比如使用maya，或者别的方式，大概说下，就能顺着这条路径去搜索，不然就是不断的寻找到一条路径，比较耗时

**Comment by Wei-Chen-hub** [comment]
可以使用blender的smplx相关插件，将输出结果导入并重定向到avatar进行渲染

**Comment by ruolunhui** [comment]
好的 非常感谢你
