### ISSUE TITLE
what's version of mmdet?

### ISSUE THREAD

**Issue by tszhang97** [caizhongang/SMPLer-X#4]
There are some errors when using mmdet. The version of mmcv is 1.7.1, and only supports mmdet 2.27.2. However, simple code like this
model = init_detector(config_file, checkpoint_file, device='cuda:0') not work. So what's the version of mmdet?

**Comment by caizhongang** [comment]
Hi @tszhang97,

We are using 

- mmcv-full==1.7.1
- mmdet==2.26.0
- mmpose==0.28.0

in our experiments. Hope this helps!

**Comment by liubc-ai** [comment]
> Hi @tszhang97,
> 
> We are using
> 
> * mmcv-full==1.7.1
> * mmdet==2.26.0
> * mmpose==0.28.0
> 
> in our experiments. Hope this helps!

Hi, I wonder why I use your provided version, but raise an error like: AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=1.3.8, <=1.6.0.
Look forward for your kind reply.
