### ISSUE TITLE
recover mesh

### ISSUE THREAD

**Issue by ahuilove** [caizhongang/SMPLer-X#43]
For each image,while inferencing,there is a npz file in output.So how can I recover 3D model image using the npz file

**Comment by caizhongang** [comment]
Hi @ahuilove , I'm not sure if I got your question correctly.
- if you are referring to overlaying the 3D model on the image, you may refer to this [section](https://github.com/caizhongang/SMPLer-X?tab=readme-ov-file#2d-smplx-overlay).
- if you are referring to obtain the 3D human mesh, our npz contain all necessary SMPL-X parameters, you may use the forward function to obtain the vertices and faces as in [here](https://github.com/caizhongang/SMPLer-X/blob/74bc864f661e5b8d3757111606d27a7ddcc6ead2/main/render.py#L37-L40).
