### ISSUE TITLE
Could find no file with path '../demo/results/walking/img/%06d.jpg' and index in the range 0-4

### ISSUE THREAD

**Issue by Eileem** [caizhongang/SMPLer-X#46]
When I try to inference, it shows these errors. Can someone tell me why and how to deal with it?
![image](https://github.com/caizhongang/SMPLer-X/assets/110441053/d9f7c220-af0a-44b4-aaea-8e0344d0f6ec)

**Comment by Eileem** [comment]
By using the pipeline here, it shows that: OSError: Failed to read input.png/000001.png. Seems this is why my inference fail. How can I deal with this problem?
https://github.com/caizhongang/SMPLer-X/issues/22#issuecomment-1789266037

**Comment by Wei-Chen-hub** [comment]
Seems you are trying to inference on an single image, please restructure it like a video. (with only 1 frame) 

i.e. input.png -> input/000001.jpg

Then use ".../input" as the input arg.

**Comment by Eileem** [comment]
> Seems you are trying to inference on a single image, please restructure it like a video. (with only 1 frame)
> 
> i.e. input.png -> input/000001.jpg
> 
> Then use ".../input" as the input arg.
> 
> P.S. Performance won't be impacted by an image format change.

thanks, I have successfully inferenced. Appreciate for your helping.

**Comment by xiaobizi** [comment]
> 似乎您正在尝试对单个图像进行推理，请像视频一样对其进行重组。（只有 1 帧）
> 
> 即 input.png -> input/000001.jpg
> 
> 然后使用 “.../input” 作为输入参数。
> 
> P.S. 性能不会受到图像格式更改的影响。
你好，在进行推理时我也发生了这个问题，请问具体是修改哪里的输入参数
