### ISSUE TITLE
Bad prediction quality out of the box (wrong config?)

### ISSUE THREAD

**Issue by isarandi** [caizhongang/SMPLer-X#55]
Thanks for releasing this work!
I'm trying to make predictions on images using inference.py, but the results look very misaligned compared to the image data. I didn't change anything, other than the fixes mentioned in the FAQ to get it running.

This is the output as drawn by this codebase:
![image](https://github.com/caizhongang/SMPLer-X/assets/6182426/79d7fad0-181a-43d7-8d2b-0e46a6e35b35)

And I get the same if I project the saved obj file myself using the saved intrinsics json data:
![image](https://github.com/caizhongang/SMPLer-X/assets/6182426/a261cc32-5fc5-474c-8310-f055cb6e1d39)

Based on the quantitative evaluation results, the output should be much better aligned, I wonder if something is configured wrong.

**Comment by GhostLate** [comment]
Same here #54 #45 #41

**Comment by isarandi** [comment]
The HuggingFace demo gives the same result, so I think this is the real result.
