### ISSUE TITLE
[Confusion] Pretrained Model about ViTPose

### ISSUE THREAD

**Issue by jameskuma** [caizhongang/SMPLer-X#63]
Dear authors, thank you for this awesome work!

I am working on this repo and I feel confused about `ViTPose` pretrained model.

As you describe in `README.md`, I should follow `OSX` to prepare models but I only see that `OSX` need me to download model with these names, like `osx_vit_b.pth` and etc. 

However, I find in your file tree, the name of vit-pose model should be `vitpose_base.pth` and etc. 

So I am confused about this, and could you help me clear this or you could share the link of these pretrained vitpose model that you use in your paper? (Since I also check vit-pose repo to find a bunch of weights and dont know which to download)

Best regards

**Comment by awfuact** [comment]
Hi @jameskuma, I am also confused about the `ViTPose` pretrained model. Which checkpoint did you end up downloading?

**Comment by Dratlan** [comment]
Hi @awfuact ,I'm also encounter this problem,did you figure it out? Thanks

**Comment by awfuact** [comment]
Hi @Dratlan, I found all pretrained things and models here: https://huggingface.co/camenduru/SMPLer-X/tree/main

**Comment by Dratlan** [comment]
@awfuact Thanks
