### ISSUE TITLE
How to setup DDP without SLURM. I have 2 GPUs on one machine and want to run the traning script on a small dataset.

### ISSUE THREAD

**Issue by rmheyg** [caizhongang/SMPLer-X#72]
Hi I have one machine with 2 GPUs and around 5000 frames with GT SMPLX. I wanted to run the training script but I can't figure out the DDP setup. I have set the world_size=2, and used mp.spawn to allocate rank but it is not working

**Comment by rmheyg** [comment]
Got it

**Comment by shuaiqidenanhai** [comment]
Hi, can you tell me how to solve it? Thanks.

**Comment by shuaiqidenanhai** [comment]
@rmheyg
