### ISSUE TITLE
random output on inference with pretrained model

### ISSUE THREAD

**Issue by noeykan** [caizhongang/SMPLer-X#8]
Hi,

I've tested inference with your pretrained model, but the result seems random value.
As I tried to debug this, input image cropped was okay.

![000471](https://github.com/caizhongang/SMPLer-X/assets/16462167/4006e70a-bcfa-4d16-91b4-62e537c6dcf9)

I've tested all pretrained models but failed.

Could you check them again?

**Comment by caizhongang** [comment]
Hi @noeykan , this doesn't seem right. Have you checked if you loaded the pretrained model successfully? PyTorch may not issue a warning if the loading fails.

**Comment by noeykan** [comment]
@caizhongang Oh, I fixed this problem. It was my mistake.
Because of some gpu errors from my computer, I changed the code in common/base.py as below at first and it made the random results as I posted before.
---
@@ -334,7 +334,8 @@ class Demoer(Base):
         # prepare network
         self.logger.info("Creating graph...")
         model = get_model('test')
-        model = DataParallel(model).cuda()
+        # model = DataParallel(model).cuda()
+        model = model.cuda()
         ckpt = torch.load(cfg.pretrained_model_path)
---

I thought these changes had not affected the result, but when I rolled back my modifications, I could see the right results outputted from the inference pipeline.

Thank you.
