### ISSUE TITLE
Any reason for choosing mmcv_full from sensetime?

### ISSUE THREAD

**Issue by noeykan** [caizhongang/SMPLer-X#9]
Hi,

Do you have any reason for choosing mmcv_full from sensetime?

```
wget http://download.openmmlab.sensetime.com/mmcv/dist/cu113/torch1.12.0/mmcv_full-1.7.1-cp38-cp38-manylinux1_x86_64.whl
```
I couldn't connect to that link, so I chose to use openmmlab's but I'm curious about this.

Thanks!

**Comment by caizhongang** [comment]
Hi @noeykan , thank you for pointing it out. We have updated the install document to fix this problem. Please let us know if the problem is solved.
